### ISSUE TITLE
Create group (user)

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#132]
As a prospective customer, I want to be able to create my group, so that I can try out Civinomics functionality.

**Comment by rskoenig** [comment]
![1_city_signup_form](https://cloud.githubusercontent.com/assets/4564957/26607574/099f3606-454c-11e7-841b-df82d3fb2b85.png)
![2_city_signup_form_confirm](https://cloud.githubusercontent.com/assets/4564957/26607579/0f7100f0-454c-11e7-9712-bbb6f0895c54.png)
![3_email_notification_new_city](https://cloud.githubusercontent.com/assets/4564957/26607584/12b3b97e-454c-11e7-9fff-c169a9073d90.png)
![4_city_signup_form_basic_info](https://cloud.githubusercontent.com/assets/4564957/26607586/15bdce70-454c-11e7-8d85-21814bb832a7.png)
![4 5_city_signup_form_basic_info](https://cloud.githubusercontent.com/assets/4564957/26607588/1937f4fe-454c-11e7-97d1-17272133e53b.png)
![5_city_signup_form_import_meeting](https://cloud.githubusercontent.com/assets/4564957/26607591/1c7186f8-454c-11e7-8600-33060e1b3a1c.png)
![6_city_signup_form_import_meeting_2](https://cloud.githubusercontent.com/assets/4564957/26607593/20553dfa-454c-11e7-9a5a-bf8cfac9e48e.png)

**Comment by drew-moore** [comment]
This is done*, pending acceptance tests. 

* Given a logged-in user, this is implemented more or less as wireframed. The UX flow for creating a new user account and group at the same time needs refinement, but that should be regarded as a separate issue.

**Comment by rskoenig** [comment]
Acceptance criteria:
A previously unregistered user can create a new account and a group in one continuous process.

Acceptance test 1:
- As an unregistered user, go to civinomics.com
- click on create group
- follow on screen instructions
- you should have an account and a group

Acceptance test 2:
- As the author of a group sign in to your group and edit the name
- click save
- as an un-registered user, open a new browser window and use a direct link to navigate to the group
- confirm name change

**Comment by rskoenig** [comment]
- I can't click "create group" and don't immediately know why. It's unclear to me whether "Icon URL" is a required field.
- Tried toggling "Does group have an admin account" (which doesn't make much sense to me), and entering an address. Still can't create group.
<img width="638" alt="cantsave1" src="https://user-images.githubusercontent.com/4564957/27151941-0ec96b0e-5101-11e7-93be-fb1618408914.png">
<img width="639" alt="cantsave2" src="https://user-images.githubusercontent.com/4564957/27151942-0ecad48a-5101-11e7-85f0-1b7b6c1157a0.png">

**Comment by rskoenig** [comment]
- On sign up modal:
"We need you to sign in to create a group."
Consistently use "sign up" and "log in" not "sign in, sign up, login, log in, and log up"

- On signup modal:
strange that the form gets cut off with so much space on the modal still unused

- After signing up, I had no indication of what to do next. No success message. I had to know to check upper right hand corner for user icon. 

- Tried to create a meeting after creating my group and confirming my email. Failed silently.

![failed_silently](https://user-images.githubusercontent.com/4564957/27153097-08988e64-5105-11e7-91a7-c91f4b529bea.png)
![nosuccessmessage](https://user-images.githubusercontent.com/4564957/27153095-0886457e-5105-11e7-8dd6-39a7a00f0129.png)
![formprematurecutoff](https://user-images.githubusercontent.com/4564957/27153096-08967728-5105-11e7-9460-66a78df86566.png)

**Comment by rskoenig** [comment]
Acceptance test 2 failed - can't navigate back to the group I created after logging out. Am logged into Austin City Council instead.

![screen shot 2017-06-14 at 1 30 03 pm](https://user-images.githubusercontent.com/4564957/27153327-dd704a28-5105-11e7-8d7b-11cb90de9a40.png)

**Comment by drew-moore** [comment]
Ah, we were updating the groups entry for representative user objects but not the admin. 

Fixed now - pls try again.

**Comment by rskoenig** [comment]
Still an issue. I create a group. Confirm email. Signout. Signin. I'm on Austin CC page, not my group.
